# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  kernel_config = debug
  k_config = debug

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := kernel k

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

kernel: k
ifneq (,$(kernel_config))
	@echo "==== Building kernel ($(kernel_config)) ===="
	@${MAKE} --no-print-directory -C kernel -f Makefile config=$(kernel_config)
endif

k:
ifneq (,$(k_config))
	@echo "==== Building k ($(k_config)) ===="
	@${MAKE} --no-print-directory -C libc -f Makefile config=$(k_config)
endif

clean:
	@${MAKE} --no-print-directory -C kernel -f Makefile clean
	@${MAKE} --no-print-directory -C libc -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   kernel"
	@echo "   k"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"